/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface InfBarcodeScanner {
    }
}
declare global {
    interface HTMLInfBarcodeScannerElement extends Components.InfBarcodeScanner, HTMLStencilElement {
    }
    var HTMLInfBarcodeScannerElement: {
        prototype: HTMLInfBarcodeScannerElement;
        new (): HTMLInfBarcodeScannerElement;
    };
    interface HTMLElementTagNameMap {
        "inf-barcode-scanner": HTMLInfBarcodeScannerElement;
    }
}
declare namespace LocalJSX {
    interface InfBarcodeScanner {
    }
    interface IntrinsicElements {
        "inf-barcode-scanner": InfBarcodeScanner;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "inf-barcode-scanner": LocalJSX.InfBarcodeScanner & JSXBase.HTMLAttributes<HTMLInfBarcodeScannerElement>;
        }
    }
}
